### ISSUE TITLE
v1.1.0 release tasks

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#103]
- [x] Rebase Develop (Casey)

Testnet Release:
- [x] Create pre-release v1.1.0 (Casey)
- [x] Create Release Notes (Eric)
- [x] Update releases.md, label as "pre-release" (Casey)
- [ ] Create msigs for Testnet (Casey/Bohdan)
- [ ] Post msig and release info to FIO Testnet 

Mainnet Release:
- [ ] Update releases.md with final contract info (Casey)
- [ ] Create msigs for Mainnet (Casey/Bohdan)
- [ ] Post msig and release info to FIO Mainnet and FIO
- [ ] Send API/History node upgrade notifications to all channels (Eric)

**Comment by dapixcasey** [comment]
Rebase PR #126 has been submitted

**Comment by ericbutz** [comment]
Closing this out tracking in Jira.
