### ISSUE TITLE
EOSIO 1.8.13 stability updates

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#104]
Review eosio 1.8.13 release to decide which fixes we want to pull into FIO.

**Comment by adsorptionenthalpy** [comment]
Bringing in the changes from EOSIO 1.8.13 
https://github.com/EOSIO/eos/releases/tag/v1.8.13

Looking into the commits from these EOS PR numbers:
https://github.com/EOSIO/eos/pull/8678
https://github.com/EOSIO/eos/pull/8680
https://github.com/EOSIO/eos/pull/8682
https://github.com/EOSIO/eos/pull/8742
https://github.com/EOSIO/eos/pull/8705
https://github.com/EOSIO/eos/pull/8722/
https://github.com/EOSIO/eos/pull/8715

**Comment by ericbutz** [comment]
Tracked as part of EOSIO 2.x upgrade. https://fioprotocol.atlassian.net/browse/BD-1717
Closing.
