### ISSUE TITLE
FIP-4: QA Tests for removePublicAddress

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#108]
Developers need to take on more of the initial QA so Pawel can focus on requirements and design. As part of that I would like the developers to take a cut at using the FIO TypeScript SDK test harness as a possible solution for QA testing. It allows for calls into the ABI and into clio directly so is fairly flexible.

As a first step let's implement some tests for FIP-4. We can get some use cases from Pawel and see how difficult it is to implement those in JS.

The JS test harness can be installed and run from:

https://github.com/dapixio/fio.test

The current utils and code is in rough form and we will need to evolve it to make it more efficient if we decide to use it

**Comment by ericbutz** [comment]
Link to epic #132

**Comment by edrotthoff** [comment]
I added simple success tests for remove public addresses and remove all public addresses, more comprehensive tests should be added to meet the test plan for remove public address. 

https://github.com/dapixio/fio.test/pull/4
