### ISSUE TITLE
Unlinkauth missing from action mapping

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#128]
Bohdan Kossak(opens in new tab)  4:54 AM
Hi, one thing found today when was updating permissions for our account and try to remove no needed one (using clio)..

**Comment by ericbutz** [comment]
Adam A. 8:12 AM
Ah must be missing from the action mapping. I’ll take a look shortly and let you know.

**Comment by ericbutz** [comment]
Todd Garrison(  9:41 AM
@Eric when you open the defect ticket, make a note that unlink auth is missing a fee param:
```
{
    "name": "unlinkauth",
    "base": "",
    "fields": [
      {
        "name": "account",
        "type": "name"
      },
      {
        "name": "code",
        "type": "name"
      },
      {
        "name": "type",
        "type": "name"
      }
    ]
  },
```

**Comment by adsorptionenthalpy** [comment]
Ed 9:50 AM
@Todd Garrison  @Luke Stokes @Adam A. I looked at unlink auth, and since the cal reduces state, there is not a fee on the call…this is intentional…so i am not sure that there is more work than the ABI for that..
