### ISSUE TITLE
In get_obt_data fio_request_id is set to 0 when it was empty, but 0 is an actual fio_request

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#137]
In get_obt_data fio_request_id is set to 0 when it was empty, but 0 is an actual fio_request.

Pawel  12:20 PM
I'm not sure I understand. When I call get_obt_data I get a record which says fio_request_id = 0. It could either be referencing FIO Request with id of 0, or it could be saying there is no corresponding fio request. How am I supposed to know which one is which?

Ed  12:25 PM
that return should be a signed int instead of uint64_t and should be negative or something when no id.. its a bug

**Comment by edrotthoff** [comment]
there are several tactics that can be employed to solve this, the first is to change the value of the return id to be a signed int and return a negative value when there is not a FIO Request id, this may have impact on the fio sdks, and wallet integrations as each may need to have logic added to interpret this correctly. the next is to permit id 0 (though valid) to have the meaning that there is not a request id, this will eliminate the impact on the sdks, but will affect the maintenance of the protocol. For development purposes we will need to always ensure that a 0 request is made and on the chain...wallets will need to be coordinated to ensure they are filtering the 0 value correctly...

**Comment by ericbutz** [comment]
It was determined that it is acceptable to have fio_request_id = 0 when it is an OBT record with now associated Request. 

Closing
