### ISSUE TITLE
Allow top 42 BPs to set fee ratios and multiplier

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#147]
Creating an issue to track discussions regarding enabling the top 42 BPs to be able to set fee ratios and multipliers so they can "signal" their fee intentions and so that when they move into top 21 their fees are ready to go.

**Comment by pawmmm** [comment]
If we did that we would need to add fees to submit_fee_ratios and submit_fee_multiplier as there would now be risk of attacking the blockchain without cost.

The cost to register as a producer is a one time cost.

**Comment by RalfWeinand** [comment]
Maybe a limited number of free fee updates per BP per day before a fee kicks in?

**Comment by pawmmm** [comment]
There already is a limit:
* 1 hour (24 times a day) for fee ratios
* 2 minutes (720 times a day) for multiplier

We can raise it, but at the end of the day a single entity can pollute the blocklog and state for a single fee (registration of BP) for life.

**Comment by edrotthoff** [comment]
so, If a producer is in the top 21, perhaps there is no fee, and if they are in the lower 21, then they pay a fee....we could be generous and say the first setting of ratio and multiplier is free for these lower 21 and then every set after that is fee based...this would encourage the proper setting of fee votes as recommended....(set the ratios one time, and use the multiplier to adapt the fees as the value of the token changes.)...in this way we would provide the lower BPs a way to state their intentions for fee votes and gain reputation in the community without a cost (as long as they are thoughtful on the first round of setting ratios)....

**Comment by ericbutz** [comment]
This request is now part of FIP-10 (https://github.com/fioprotocol/fips/blob/master/fip-10.md). Closing.
