### ISSUE TITLE
fio.fee contract optimizations

### ISSUE THREAD

**Issue by cc32d9** [fioprotocol/fio#154]
fio.fee contract as of 60e0f506ba5ad99411ed8519b86c1fbc7b828c9c in master branch:

Line 175, 293: `actor` should be of type "name", to let the serialization API check the validity and save on conversion time.

Lines 194, 203: index object initialization involves looking up in nodeos tree of indexes, and it does not need to be within the loop. These objects can be initialized only once.

Line 209: the while() loop goes through every endpoint in the votes table for this voter, and every iteration requires a deserialization of a vote object. This loop can be done cheaper if there's a 64bit hash index for (voter, endpoint) tuple. In this case, there would be one lookup most of the time, and more lookups in extremely rare occasions when the hashes collide.

Lines 234-239 are obsolete because it's cheaper to modify an existing row instead of deleting it and emplacing a new one.

Line 39: `map<string, double> producer_fee_multipliers_map;` should be defined as <uint64_t, double>`  in order to save on repetitive conversion from `name` to `string`.

`update_fees()` should be reorganized in the following way: whenever a new vote is cast, the smart contract needs to keep a table of endpoints that need an update. Then `update_fees()` has a limit of calculations as an argument, and stops processing after reaching this limit. So it gets the first endpoint from the list of those needing an update, calculates the median, and keeps track of the number of executed calculations (basically, the number of voters). It stores the update and deletes the endpoint name from the update queue, and checks if the limit of calculations is reached. If so, it finishes the action. Subsequent calls to `update_fees()` will continue processing what is left.  

If no fees require an update, the action may succeed or reject, depending on requirements. If it's triggered by an external oracle, it's beneficial to reject and save on blockchain resource.

Floating point fees can be replaced with an integer and 1000x multiplier. That will reduce the costs of calculations.

Lines 157-161: it only makes sense to initialize those indexes in constructor which are utilized in every action. The constructor is called at the start of every action, and index initialization takes time (nodeos looks up in the global table of smart contracts). Normally the action code would only initialize those tables which are in use in this action.

Line 279: the updatefees action does not require any authorization, and it's probably better to let anyone trigger the recalculations. Then BP can do it without a multisig.

**Comment by edrotthoff** [comment]
it will be great to get some timings on this before and after to really understand the improvements these suggestions bring to the code performance..

**Comment by edrotthoff** [comment]
thanks for this feedback @cc32d9!!

**Comment by cc32d9** [comment]
100k multiplications and 100k divisions for double take about 3.5ms, and same amount of operations with uint64 is 1.2ms.  This is a very rough calculation. But update_votes did not occupy 100k operations, so it should be something else

**Comment by cc32d9** [comment]
that was on EOSVM in eosio 2.0

on WABT, 10k multiplications and 10k divisions took 5ms with double, and 2.9ms with uint64

**Comment by edrotthoff** [comment]
line 194, 203   it is important to note that modern compilers perform a process of loop expansion, so the code does not execute the way you might be reading it. loop expansion commonly places data items into memory locations and expands the loop thus eliminating this concern at runtime...this makes this suggestion a possible stylistic preference of the developer in this regard...

**Comment by edrotthoff** [comment]
we are considering to move the update of fees out of the unblock, and into a dedicated endpoint that will perform a fixed amount of work, which can be called repeatedly and will pick up where it left off when called, or return a no work exception. the update fee logistics and strategy will be re-worked when this work is performed, so updating this version of the code may not prove useful at this time..

**Comment by edrotthoff** [comment]
I hav been working on the FIO fee voting redesign and as part of that effort I started with the changes suggested here, I observed no significant performance increases after making the changes....im keeping these types of changes in the new version of the fee update code to avoid these kinds of stylistic debates in the future...

**Comment by edrotthoff** [comment]
this issue can be closed.

**Comment by ericbutz** [comment]
As per discussion above. Closing.
