### ISSUE TITLE
Determination of date and time of forking deadline for Test net rollout of gemini

### ISSUE THREAD

**Issue by edrotthoff** [fioprotocol/fio#199]
This issue tracks the determination of the forking deadline for test net rollout of gemini.

The forking deadline must be set for the test net and main net releases (main net will be addressed separately).

The forking deadline should be the block time that the FIO protocol will begin using the new action mapping that is in state. After this time any nodes that have not upgraded to the gemini release for testnet will fail to work properly.

the forking deadline should include adequate time (and some cushion) for the following activities
1) coordinate all BPs and perform the upgrade of the chain code to the gemini binaries.
2) verify the upgrade of all who are required to upgrade.
3) perform the MSIG for the set code of the gemini system contract modification (must happen after step 2)
4) perform the MSIG to add the 50-60 actions (by calling the new system contract action called addiction).

The present idea is to set the forking deadline for test net to be Monday August 10 2020 at 12pm UTC
(6am MST).

please add your comments and suggestions and we will try to finalize the time In the next 24 hours (deadline for decision is July 23 7pm UTC)...

Thank you for your participation.

**Comment by ericbutz** [comment]
EOSUSA Michael, [22.07.20 12:11]
so i guess it think on testnet after seeing the participation of everyone on this round wed probably be able to pull it off in a week best case.  say a day for u to push the code, a few days for the bps to replay and prep, then a day for u guys to push the contracts actions.  2 weeks if u wanted to have some cushion.... just my 2 FIO, curious what others think

**Comment by edrotthoff** [comment]
Presently the idea is to be somewhat aggressive and rollout gemini in one week, this would be Aug 2 2020 for the forking deadline...

**Comment by Rossco99** [comment]
We are happy with this date

**Comment by ericbutz** [comment]
Date selected. Tracked in: https://github.com/fioprotocol/fio/issues/213
Closing.
