### ISSUE TITLE
FIO Fee Update

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#203]
Tracks discussion surrounding FIO BP update of FIO Fees. 

The following price data is taken from Coingecko FIO Protocol USD (Historical Data)
https://www.coingecko.com/en/coins/fio-protocol/historical_data/usd#panel

snapped_at | price
2020-07-13 00:00:00 UTC | 0.113946112
2020-07-14 00:00:00 UTC | 0.113946112
2020-07-15 00:00:00 UTC | 0.086577099
2020-07-16 00:00:00 UTC | 0.093932881
2020-07-17 00:00:00 UTC | 0.084144208
2020-07-18 00:00:00 UTC | 0.083985383
2020-07-19 00:00:00 UTC | 0.083476238
2020-07-20 00:00:00 UTC | 0.124258708
2020-07-21 00:00:00 UTC | 0.148377484
2020-07-22 00:00:00 UTC | 0.181089225
2020-07-23 00:00:00 UTC | 0.181444731

11 day average price: 0.118
7 day average price: 0.127
5 day average price: 0.144

Current FIO Fee for register_fio_address: 40 FIO

Current price of register_fio_address in USD using 11 day average: 40 FIO * 0.118 = $4.71
Current price of register_fio_address in USD using 7 day average: 40 FIO * 0.127 = $5.07
Current price of register_fio_address in USD using 5 day average: 40 FIO * 0.144 = $5.75

Target price of FIO Address is $2.00

Suggested FIO Fee for register_fio_address using 11 day average: $2.00 / $4.71 * 40 ~ 17 FIO (multiply current fee by .42)
Suggested FIO Fee for register_fio_address using 7 day average: $2.00 / $5.07 * 40 ~ 16 FIO (multiply current fee by .39)
Suggested FIO Fee for register_fio_address using 5 day average: $2.00 / $5.75 * 40 ~ 14 FIO (multiply current fee by .34)

**Proposed: Multiply current fees times 0.35**
(Current fees: https://www.alohaeos.com/tools/fiofees)

The new register_fio_address fee would be 14
If FIO trades at ~$0.14 a FIO Address would cost $0.14 * 14 = $1.96

The best way to think of this is to agree on what the assumed exchange rate might settle at in the near future. This proposal suggests $0.14

**Comment by Rossco99** [comment]
In my opinion a slightly cheaper address is better than an address that is too expensive.. I agree with your $0.14 / FIO rate right now.

**Comment by robrigo** [comment]
$0.14 sounds fair to me!

**Comment by ericbutz** [comment]
Good point that slightly cheaper is better than too expensive. To be more conservative we could assume an exchange rate average of $0.15 which would put the price of an address at ~13 FIO. Then we would multiply all current prices by 0.325.

**Comment by jrosich** [comment]
$0.14 its a reasonable rate

**Comment by ericbutz** [comment]
Fee was updated by BPs. Closing.
