### ISSUE TITLE
Determine date and time of forking deadline for Mainnet rollout of gemini release v2.x

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#214]
This issue tracks the determination of the forking deadline and schedule for the **Mainnet** rollout of Gemini release (currently tagged as https://github.com/fioprotocol/fio/releases/tag/v2.0.0-rc1).

Proposed rollout schedule:

- Week of August 10 - Reach out to Exchanges and Wallets to ask about upgrade timing.
- Milestone 1 (Friday Aug-14) - Announce release and schedule to FIO community.
- Milestone 2 (_M1 + 3 weeks_ = Sep-4) - All Mainnet nodes must be upgraded to gemini
- Milestone 3 (_M2 + 1 week_ = Sep-11) - FIP-12 system contract msig approved on mainnet. This enables the calling of addaction/remaction.
- Milestone 4 (_M3 + 5 days_ = Sep-16) **Mainnet forking transaction:** addaction msigs approved for 50-60 fio actions
- Milestone 5 (_M3 + 1 week_ = Wed Sep 23 16:00:00 UTC 2020 ) The new actions table needs to be populated with all of the allowed actions in the fio protocol. If Milestone 4 is not fully executed by this date the blockchain will reject all actions that are not in the new whitelist table.

This is a 5 week schedule from announcement to Mainnet activation.

The important steps are Milestones 4 and 5. The real fork is happening with Milestone 4. Though there is a "forking date" in the chain code that is mentioned in Milestone 5, the reality is that if a node has not upgraded by the time the addaction msig is executed in Milestone 4 they will be already forked by the time we get to Step 5.

**Comment by edrotthoff** [comment]
we should identify the key players list for main net. (do this before we begin)
we should decide what tools or social networking avenues, or blog will be used to communicate amongst the key players (do this before we begin)
we should record the following audit trail for the key players (received notification to upgrade, upgrade performed, notified of impending forking event and time window of forking event (the MSIG for the addiction), notified that forking event has passed (addiction is completed). Then we wait for the final switchover date/time.

**Comment by edrotthoff** [comment]
I think we should consider to add just a bit more "slop" into the dates, IE add a couple of days to the deadline, 3 days to get the addiction msig seems adequate, but if/when something unexpected happens we will be thankful for a bit more time on this. I would think its safe to add a couple of days to the final switchover (which is hardcoded in the code)...this puts the final switchover mid week during the week ending Sept 11. This looks like a great plan...

**Comment by edrotthoff** [comment]
unknowns/risks -- 
    
    necessary time to coordinate the exchanges and wallets.
           -- start this process now.
    what happens if/when one or more of the key players decides they cannot continue In the transition?   (unboink/rollback main net, or accept them being forked out)

**Comment by edrotthoff** [comment]
> unknowns/risks --
> 
> ```
> necessary time to coordinate the exchanges and wallets.
>        -- start this process now.
> what happens if/when one or more of the key players decides they cannot continue In the transition?   (unboink/rollback main net, or accept them being forked out)
> ```

this was discussed offline, DPOS doesn't care who you might be in the scheme of things, we need to socialize the change in the community, then go forward with the plan. anyone that doesn't do this upgrade will fork and that is what it is.

**Comment by edrotthoff** [comment]
one more idea. do we need marketing involvement in this rollout? not sure if this is necessary, but it might be useful. I am unsure..

**Comment by ericbutz** [comment]
Added dates to the schedule above.

**Comment by ericbutz** [comment]
Proposed fork date: Wed Sep 23 16:00:00 UTC 2020

**Comment by ericbutz** [comment]
Gemini release v2.0 is complete. Closing.
