### ISSUE TITLE
fio.fee Set fee vote -- when the number of fees voted is 70 fees,  RAM usage exceeded error  for BP accounts not in the schedule

### ISSUE THREAD

**Issue by edrotthoff** [fioprotocol/fio#220]
when the number of fees voted on gets to being 70 fees, accounts that are not in the BP schedule experience a ram usage error and the vote fails to process. The work around is to split the votes into 2 tx and submit separately.

ram_usage_exceeded: Account using more than allotted RAM usage
account account name has insufficient ram; needs 36568 bytes has 32768 bytes
    {"account":"accountname","needs":36568,"available":32768}

**Comment by edrotthoff** [comment]
we should consider to add logic into the voting action to check that the size is not greater than this number, 32768 this number is enforced in the FIO core as the max ram usable for a tx..

**Comment by edrotthoff** [comment]
a spike might be to look at all fio actions, find the ones that can get larger than this (no limits on included elements) and add appropriate checks..

**Comment by ericbutz** [comment]
Tracked as FIP-10 under development: https://github.com/fioprotocol/fips/blob/master/fip-0010.md
Closing
