### ISSUE TITLE
centos    How to install nodes

### ISSUE THREAD

**Issue by satonz** [fioprotocol/fio#225]
There are no detailed installation tutorials

**Comment by adsorptionenthalpy** [comment]
Hi @satonz, check out fio.start https://github.com/fioprotocol/fio.start

**Comment by satonz** [comment]
@adsorptionenthalpy   How should I configure to connect to the main network using this tutorial

**Comment by adsorptionenthalpy** [comment]
@satonz Have you had a chance to review our knowledgebase? https://developers.fioprotocol.io/fio-chain/bp#knowledge-base-articles
The other mainnet producers can get you connected. You can meet them in the testnet telegram channel listed on the bottom of the kb article I just linked.
