### ISSUE TITLE
Member access within null pointer detected via Libfuzzer & UndefinedBehaviorSanitizer

### ISSUE THREAD

**Issue by swirsz** [fioprotocol/fio#335]
Member access within null pointer detected via Libfuzzer & UndefinedBehaviorSanitizer. 

./fuzz_parseini crash-fb8.txt 
Running: crash-fb8.txt

lib/bloom.c:95:26: runtime error: member access within null pointer of type 'struct bloom'
[crash-fb8.txt](https://github.com/fioprotocol/fio/files/7829716/crash-fb8.txt)

**Comment by ericbutz** [comment]
Not sure what this is for. Needs more information. Closing.
