### ISSUE TITLE
ZERO SUPPORT FOR USERS OR INTEGRATORS

### ISSUE THREAD

**Issue by Jesse-21** [fioprotocol/fio#365]
If you are someone here on github looking to use this protocol, they have zero support.  NONE.
I have waited close to two months for a response to my numerous support requests.
Stay clear of this project.  I have contact many of the current integrators, many who have zero support responses either.
If you delete this issue request I will have no choice but to report your project to github as well.
Support your protocol, or watch integrations leave your platform. 
Last warning. I Have tried going on 2 months now without a single response from FIO.

**Comment by adsorptionenthalpy** [comment]
" I Have tried going on 2 months now without a single response from FIO." 
When ? How ?  FIO does not provide support over github. 

For integrator support, open a Jira ticket: https://fioprotocol.atlassian.net/servicedesk/customer/portal/3/group/-1
Telegram: https://t.me/joinFIO
Discord: https://discord.gg/fio <--- Additional support here

**Comment by Jesse-21** [comment]
the support channels.  this was my last resort it took2 months to get someone to respond.  You are the first to respond anywhere about support.  Iand then someone else emailed me . I will delete my comment above.  thank you for your response.
