### ISSUE TITLE
step in decrcounter is pass by value

### ISSUE THREAD

**Issue by adsorptionenthalpy** [fioprotocol/fio#42]
https://github.com/fioprotocol/fio/blob/ea4dafb7df1ed83cca52d773fcb6d1fe6beec7a3/fio.contracts/contracts/fio.address/fio.address.cpp#L1051

Recommend:
`   void decrcounter(const string &fio_address, const int32_t &step) 
`

**Comment by ericbutz** [comment]
Resolved by #82

**Comment by ericbutz** [comment]
Fixed in https://github.com/fioprotocol/fio/pull/92
