### ISSUE TITLE
Enhance clio

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#54]
Includes enhancements to clio:

- Update clio to reflect the custom calls for FIO

- Confusing error messages in clio

**Comment by adsorptionenthalpy** [comment]
Making multisig alterations a priority based on input from @lukestokes

**Comment by adsorptionenthalpy** [comment]
FIP draft opened https://github.com/fioprotocol/fips/pull/106

**Comment by ericbutz** [comment]
Tracked as initiative: https://fioprotocol.atlassian.net/browse/BD-1587

**Comment by ericbutz** [comment]
Closing. Feature was merged and is targeted for next chain release.
