### ISSUE TITLE
TPID was not processed when provided in addaddress

### ISSUE THREAD

**Issue by adsorptionenthalpy** [fioprotocol/fio#59]
KB references a tpid but it is not processed when used in addaddress action of fio.address contract
https://developers.fioprotocol.io/api/api-spec/reference/add-pub-address/add-pub-address-model

`~/fio/1.0/bin/clio -u http://localhost:8889 push action -j fio.address addaddress '{"actor":"j2x22kkddut1","fio_address":"adam@dapix","public_addresses":[{"chain_code":"BTC","token_code":"BTC","public_address":"1ERJT3s8BsYLh6M2251KF1ZPvuAADV1KEn"}],"max_fee":40000000000,"tpid":"adam@dapix"}' -p j2x22kkddut1@active`

`adam$ ~/fio/1.0/bin/clio -u http://localhost:8889 get table fio.tpid fio.tpid tpids`

`{
  "rows": [],
  "more": false
}
`

**Comment by aaroncox** [comment]
Seeing the same thing using our internal tooling. 

I submitted [a transaction for regaddress](https://explorer.fioprotocol.io/transaction/a7391995f4d6c9f9a41a89496782d133e448b22b32e44a1fa441268980296ee6) which included a tpid on mainnet, and the table within fio.tpid remained empty.

The public key (FIO5nambcL1f7ot8yJTsf3zfPkSpeAB4JBE4qWPUdJbCWQJpXEUiy), account (qcic4ydb3vqh) has a registered address (proxy@greymass), and is also registered as a voting proxy.

**Comment by adsorptionenthalpy** [comment]
> Seeing the same thing using our internal tooling.
> 
> I submitted [a transaction for regaddress](https://explorer.fioprotocol.io/transaction/a7391995f4d6c9f9a41a89496782d133e448b22b32e44a1fa441268980296ee6) which included a tpid on mainnet, and the table within fio.tpid remained empty.
> 
> The public key (FIO5nambcL1f7ot8yJTsf3zfPkSpeAB4JBE4qWPUdJbCWQJpXEUiy), account (qcic4ydb3vqh) has a registered address (proxy@greymass), and is also registered as a voting proxy.

In this instance, tpid should be in the address@domain format. There is a FIO public key in the field. 
Important to note that this is supposed to act passively so the rest of the transaction can succeed.... so you will not get an error.

**Comment by aaroncox** [comment]
That was my particular problem - using a FIO Address did actually create the record in the fio.tpid table. The corrected [transaction is here](https://explorer.fioprotocol.io/transaction/9d55932b79bf752fd296d3056492263e85c197597245ac710c9c1c019d414232), which created the table entry.  

I'll continue to monitor the table as development continues to see if I can identify any other calls that may not be working, but regaddress appears to work.
