### ISSUE TITLE
Move system contracts to separate repo

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#60]
We would like to move the system contracts out of fio and into a fio.contracts repo. This is similar to what EOSIO did with their contracts:

https://github.com/EOSIO/eosio.contracts

**Comment by dapixcasey** [comment]
I recommend that this issue be resolved as the last task prior to the release of v1.1.0

**Comment by ericbutz** [comment]
Done. New fio.contracts repo.
