### ISSUE TITLE
Define maximum string length in fio.address

### ISSUE THREAD

**Issue by cc32d9** [fioprotocol/fio#67]
`fio.address` accepts any string length for name and domain strings, and it causes a difficulty in integrating FIO with other systems. There should be a reasonable maximum length of name and domain, maybe 256 symbols.

**Comment by dapixcasey** [comment]
We have the following limits in place:

FIO Address:
-  Min: 3
-   Max: 64
-   Characters allowed: ASCII a-z0-9 - (dash) @ (at sign)
-   Characters required:
         only one @ and at least one a-z0-9 on either side of @.
         a-z0-9 is required on either side of any dash
-   Case-insensitive

FIO Domains
- Min: 1
- Max: 62
- Characters allowed: ASCII a-z0-9 - (dash)
- Characters required:
     a-z0-9 is required on either side of any dash
- Case-insensitive

**Comment by cc32d9** [comment]
yes, sorry, found in the code too
