### ISSUE TITLE
bind2eosio in fio.address does not validate client_key

### ISSUE THREAD

**Issue by cc32d9** [fioprotocol/fio#69]
The action `bind2eosio` accepts any string as `client_key`. Even that it's only called by system accounts, it needs to verify that the key is a valid string

**Comment by dapixcasey** [comment]
I agree that `bind2eosio` can be locked down a more with expression validation. I purpose a simple !null || >128 would be enough since only accountmgr is able to use this action.

**Comment by adsorptionenthalpy** [comment]
- bind2eosio action is only called by auto account creation for domain/address registrations and FIO transfer via public key, so there is a pubkey binding for the new address.
- the parent actions that call bind2eosio perform the validation on the parameter. To add a redundant check makes me a bit uncomfortable, but I see other opportunities for code refactoring anyway so I will add this additional check. Didn't like the parameters were pass by value either so I corrected this too.

**Comment by ericbutz** [comment]
Resolved by #81

**Comment by ericbutz** [comment]
Deployed to mainnet as part of the v1.2.0 fio.contracts release.
