### ISSUE TITLE
ABI error in fio.address, "domains" table: wrong type for "expiration"

### ISSUE THREAD

**Issue by cc32d9** [fioprotocol/fio#71]
Current ABI returns uint32 for `expiration` field in "domains" table, but the contract defines it as uint64. This breaks decoding of domains in state history.

```
    },{
      "name": "domain",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "name",
          "type": "string"
        },{
          "name": "domainhash",
          "type": "uint128"
        },{
          "name": "account",
          "type": "name"
        },{
          "name": "is_public",
          "type": "uint8"
        },{
          "name": "expiration",
          "type": "uint32"
        }
      ]
    },{
```

**Comment by dapixcasey** [comment]
The appropriate type should be `uint64`. This should not break the contract due or cause a table migration.

**Comment by cc32d9** [comment]
it breaks the decoding of state history, so data analysis becomes difficult

**Comment by ericbutz** [comment]
We are doing other ABI updates for the next version. Included this in the list.

**Comment by adsorptionenthalpy** [comment]
Performed some local tests, setting new abi had no negative impact operation wise. Can continue to register and read domains from table. Concerns regarding decoding state history remain and needs further discussion.

**Comment by ericbutz** [comment]
Resolved by #78

**Comment by ericbutz** [comment]
Updating to uint64 broke the setcode for the system contracts. Need to troubleshoot this. Reopening.

**Comment by adsorptionenthalpy** [comment]
Updates: No issues are apparent when spinning up a new blockchain with these contracts.
When testing in devnet @dapixcasey found changing the domain expiration abi type to 64 can result in domain table read failures from the system contract voting.cpp. uint32_t value appears to be used instead of uint64_t and changing the domain expiration type and setting the abi on a live state would require multiple table migrations.

**Comment by ericbutz** [comment]
Fixed by: https://github.com/fioprotocol/fio/pull/78
Release: https://github.com/fioprotocol/fio.contracts/releases/tag/v2.1.0
Closing
